# Generated by Django 4.2.1 on 2023-09-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=5)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
            ],
        ),
    ]
